### ISSUE TITLE
Fail if controller_service is not set

### ISSUE THREAD

**Issue by rvennam** [IBM-Cloud/logistics-wizard-webui#127]
If controller_service is not set, the UI use "" for controller root, which causes the UI to hit it's own domain.

**Comment by Twanawebtech** [comment]
ToDo: need to be checked.

**Comment by van-ibm** [comment]
Ram has an alert dialog triggered if the controller service url is not defined. I expect this is a condition found in local development (forgetting to update the .env file perhaps).  In production, the build pipeline should fail if the controller url isn't defined.  @rvennam were there other situations that prompted this issue to be created?

**Comment by rvennam** [comment]
Can't think of any. Closing
